### ISSUE TITLE
Is importing notebooks in the ui notebook a good idea ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#132]
As you may know the applications struggle on the dashboard to launch fast enough. I already received messages from impatients foes that the module was not working when in fact it was just taking it's time to load. 

I cannot display the voila spinning wheel in the dashboard as voila is launch through a command line interface BUT I think that the way we build the ui may be slowing down the process. 

In the first place I freely inspired from the first implementation of [pysmm](https://github.com/openforis/sepal_pysmm), where @ingdanielguerrero you were importing notebook into another one. But now, with our super heavy notebooks, is it still a good practice ? 
wouldn't it be faster if instead of notebooks we import python files ? 

I will do some testing on the [guidos workbench](https://github.com/12rambau/gwb) when it will be finished (it has 10 tiles, so 10 notebooks, I should really see a difference if it exist)

**Comment by ingdanielguerrero** [comment]
Yes, I agree with this, the process to load the modules is taking so long, I also was inspired by Erik but as the modules are growing, we definitely have to find some other options! thanks for take a look over this!

**Comment by 12rambau** [comment]
if every single notebook create it's own `sys.arg` environment it will be damn slow: 

https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-run 

need to check it in an heroku agnostic app but I forsee that we are going the wrong way

**Comment by 12rambau** [comment]
Ok I finally found the time to test the different behaviours and out of 100 test, with Python import and notebooks %run:

```
import pandas as pd 

ipynb = pd.read_csv("/home/prambaud/modules/ipynb/tests_ipynb.csv", names=['time'])
ipynb.time.mean()

>>>>> 14.851160000000002

py = pd.read_csv("/home/prambaud/modules/py/tests_py.csv", names=['time'])
py.time.mean()

>>>>> 14.840105555555558
```

## Consequence
- importing notebook is a good idea and execution speed is not sensible to it
