### ISSUE TITLE
Cannot instantiate widgets with custom parameters

### ISSUE THREAD

**Issue by ingdanielguerrero** [12rambau/sepal_ui#133]
As most of the widgets are written, when calling its `super()` function with default parameters, it's not possible to instantiate a widget without free parametrization.
Let's say I want to create a `sw.DownloadBtn()`, I can't instantiate it with another parametrization, such as `sw.DownloadBtn(xs5=False)` because `__init__` is getting multiple values for  `xs5 `parameter.

The solution would be the following:

```Python    
def __init__(self, text, path='#', **kwargs):
        
        self.class_   = 'ma-2'
        self.xs5      = True
        self.color    = 'success'
        self.children = [
            v.Icon(left=True, children=['mdi-download']),
            text
        ]
        super().__init__(**kwargs)
```

**Comment by 12rambau** [comment]
Excellent suggestion ! 

As I don't know when this feature will actually be added to the release (and then pushed to sepal) I highly suggest you use a workaround in your current project (and maybe open an issue for further refactoring) to share it with others that don't have access to the Master branch. 

```
toto = sw.DownloadBtn()
toto.xs5 = False
```

Whenever it will be ready on Sepal, I'll add a message in this issue
