### ISSUE TITLE
bind the values and a alert

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#15]
The only we can confirm to the end user the value that he has selected with the inputs is to use the alert. 
This confirmation is (for me) important as some widgets can have slow behaviour (dropdowns and slider mainly). 

at the moment the binding is performed with the function `bind` in `widgetBinding` module. 

I suggest to add the bind function as a method of the `Alert` object of `SepalWidget` as such : 

```py
def bind(self, input, obj, variable, output_message='The selected variable is: '):

    #create the on_event litener

    #bind the obj variable to the input v_model

    #display it in the alert

    return 
```

what do you think ?

**Comment by ingdanielguerrero** [comment]
That bind method works for me, but I also want to consider using the `observe` and `link` methods from the `traitlets` module,
i.e., in this alert class we could create a children List trait.

```python
class Alert(v.Alert, SepalWidget):
    """create an alert widget that can be used to display the process outputs"""
    
    TYPES = ('secondary', 'primary', 'info', 'error', 'warning', 'success')
    
    children = List().tag(sync=True)
    
    def __init__(self, type_='info', **kwargs):
        
        type_ = type_ if (type_ in self.TYPES) else self.TYPES[0]
        
        super().__init__(
            type_ = type_,
            text = True,
            class_="mt-5",
            **kwargs
        )
        
        self.hide()

```

And then create a callback every time the value has changed, and make sure that the value is a list.

```python
def callback(change, alert):
    if not isinstance(change['new'], list):
        alert.children = list(change['new'])
```

Then we can create a new widget... 

```python
select = v.Select(v_model='', items=["apple","orange"])
```

And bind both with the observe method.

```select.observe(partial(callback, alert=alert), 'v_model')```


What do you think? could this implementation works?

**Comment by 12rambau** [comment]
what is the advantage of using `observe` over `on_event` ? 
Can we bind multiple inputs to the same alert widget with this implementation ?
