### ISSUE TITLE
develop a non GEE dependant version of the aoi_selector 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#180]
The aoi_selector is hard coded using the GEE api, forcing any app that want to have this functionnality to be bound to GEE or to create a new one. 

I start this issue to discuss what are to possible solutions at hand and the problems to overcome : 

**Problem :**
- Whatever the modification we make, we don't want to break the already functionning modules 
- We need to continue using GAUL in GEE as it's the closet map we have to the UN maps used in the other UN products (HiH and FERM) 

**potential solutions:**
- rewire the aoi to have 2 embeded behaviour (big refactoring coming but that is necessary anyway) 
- create a second aoi selector

**Comment by ingdanielguerrero** [comment]
I believe that to make more clear code and to avoid having issues with the current implementation, the better solution would be to create a new AOI selector (I have something already working)....

**Comment by 12rambau** [comment]
and so you would double the aoi object as well right ?

**Comment by ingdanielguerrero** [comment]
I think yes... because their behaviors are different, so we could call it as LocalAoi or something like that...

**Comment by 12rambau** [comment]
I like it, if you want to start including what you have already develop, please create a new branch so that we can prepare everything separately from the rest

**Comment by 12rambau** [comment]
it will be super easy to retreive on the fly the GADM geopackages, the files links look like the following : 
`https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_FRA_gpkg.zip`

I will retrieve them at least once to create a `country_table.csv` first (because not all countries have the 6 administrative levels) to better design the dropdowns.

**Comment by ingdanielguerrero** [comment]
I just created a new branch with a draft of a local_aoi widget, I'm oppening a new discussion topic so we can chat the implementation details there https://github.com/12rambau/sepal_ui/discussions/183
