### ISSUE TITLE
Cant reclassify a ee.Image layer

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#246]
When I try to reclassify this dataset `users/dafguerrerom/ID_Uganda_example`, the following error in gee comes up:

> Error: Image.remap: Unrecognized type in 'from' list at position 0: expected a number or array, found Type<String>.

**Comment by 12rambau** [comment]
I didn't manage to reproduce your error. 

I tested it with the provided asset: `users/dafguerrerom/ID_Uganda_example`
using the band: `csnr`

As a remapping function I used the simple forest-no-forest mask that I build for testing

In GEE I get the following error:
> Error: Asset 'projects/earthengine-legacy/assets/users/dafguerrerom' does not exist or doesn't allow this operation.

So I think I have a naming problem here.

**Comment by dfguerrerom** [comment]
I forgot to remove this issue, but if I'm not wrong it was related to the mapping matrix https://github.com/12rambau/sepal_ui/blob/4147764b3a8b6fb5e137f985aed7a98d40b18292/sepal_ui/reclassify/reclassify_model.py#L493
