### ISSUE TITLE
Validate selected and add default assets to Asset Select widget

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#253]
It's nice to have a default asset for the user but it would be also nice to have a list of custom/predefined assets, so the user will have the option to select one or another and keep them in the list without losing them.
There is a missing validation of the inputs, would be nice to have an alert message once an asset is selected and store the status in the widget attributes, such as `valid` and `type`.

**Comment by dfguerrerom** [comment]
Instead of having `asset type`, I think that it would be more useful to store the full `asset_info`, so it could be used afterward.

**Comment by 12rambau** [comment]
> Instead of having asset type, I think that it would be more useful to store the full asset_info, so it could be used afterward. What do you think @12rambau ?

agreed

**Comment by 12rambau** [comment]
can we close the issue ?
