### ISSUE TITLE
Clean import indexes

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#256]
As we are using `import * from x` pattern in the `__init__.py` module files we should provide an explicit index in every module so we can avoid unexpected slashes.

see: https://www.python.org/dev/peps/pep-0008/#public-and-internal-interfaces

**Comment by 12rambau** [comment]
that's the cleanest way to proceed. 

in case you want to hide methods or class from a module you can also start their name with `_` like:

```python 
def _foo():
    print('toto')
```

and they will be ignored by `import *`

**Comment by 12rambau** [comment]
In other libs (like geemap or matplotlib) they are declared at the beginning, I checked the web and here is no standard but I also think it's more readable (you see in the first 10 lines what is available in the module) what do you think ?

**Comment by dfguerrerom** [comment]
Absolutely, I think that's the cleanest way. It is also useful to avoid importing "imported packages/modules" within the namespace.

**Comment by 12rambau** [comment]
perfect I'll add a commit for that
