### ISSUE TITLE
do we want to use conventional commits ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#259]
I discovered conventional commit when I PR things to ipyvue and I like the feature and trigger that we can associate with them. what do you think ? 

> The Conventional Commits specification is a lightweight convention on top of commit messages. It provides an easy set of rules for creating an explicit commit history; which makes it easier to write automated tools on top of. This convention dovetails with SemVer, by describing the features, fixes, and breaking changes made in commit messages.

https://www.conventionalcommits.org/en/v1.0.0/

**Comment by dfguerrerom** [comment]
I've been reading and it seems a great feature to improve the quality of the code and to align with the semantic versioning :), let's do it. 
What would be the best tool to help us in this? I've been searching and this package https://pypi.org/project/conventional-commit/  looks a good point of start, do you have alternatives?.

**Comment by 12rambau** [comment]
That's a hard one :-). I wouldn't be so restrictive I was just thinking of it as a plus for us and mybe we could build some automation on top of it (automatic release, automatic changelogs etc...)

**Comment by 12rambau** [comment]
I think I'll try to use this instead : https://github.com/commitizen-tools/commitizen

2 advantages: 
1. the templating is live with little info (works like a charm) 
2. the lib is compatible with pre-commit hooks 

I'm trying to make it work on my side but it seems promising
