### ISSUE TITLE
SepalMap is not automatically resized anymore

### ISSUE THREAD

**Issue by BuddyVolly** [12rambau/sepal_ui#282]
the map is not resized anymore when we click on the drawers

**Comment by 12rambau** [comment]
It should be handled by this script : https://github.com/12rambau/sepal_ui/blob/ee09f1bc2f0e99804621362e7b02e992b3fb070b/sepal_ui/frontend/js.py#L8

for some reason it not executed any more

**Comment by 12rambau** [comment]
with the new version of voila and Jupyter installed in SEPAL (0.2.12) Javascript code cannot be executed the same way. 
RPC seems to be the best solution as it's avoiding the injectoin of `<scripts>` tags every time it's executed
