### ISSUE TITLE
Add local tile layer (raster) inspector 

### ISSUE THREAD

**Issue by ingdanielguerrero** [12rambau/sepal_ui#29]
Would be nice if the user could use the current geemap inspector to get the pixel value of the raster image, this function is useful to inspect a raster without the need of moving to a desktop app.

**Comment by 12rambau** [comment]
Is the inspector by default on the map ?

**Comment by ingdanielguerrero** [comment]
Actually not, the inspector has to be added after creating the map with: `map_.add_control(map_.inspector_control)`

**Comment by 12rambau** [comment]
perfect because I have a lot of map in modules that don't require any inspector and I didn't want to change them all ;-)
