### ISSUE TITLE
List of oft command required in sepal_ui

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#3]
Add in the comment the oft command that you would like to see in sepal_ui

### Updated list of the oft functions in sepal_ui
- [x] oft-clump
- [x] oft-his

**Comment by ingdanielguerrero** [comment]
Same comment on #4

**Comment by 12rambau** [comment]
Useless now that I've started a lib dedicated to manipulation function
the rep is here https://github.com/12rambau/SGT
The oft file will be removed once I'm 100% sure that no function is using it any more in modules that are already in prod
