### ISSUE TITLE
do we want to display the warnings in loading_buttons ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#305]
I recently bump into this problem: let's say one of your lib is using a deprecated method from another lib but everything is still working. The warning are capture by the `loading_button` decorator and displayed in the `Alert` as a warning: https://github.com/12rambau/sepal_ui/blob/952627c0973cb03b4053fccabf79fa619fe3631c/sepal_ui/scripts/utils.py#L257

```python
# Catch warnings in the process function
with warnings.catch_warnings(record=True) as w:
    value = func(self, *args, **kwargs)

    # Check if there are warnings in the function and append them
    # Use append msg due to several warnings could be triggered
    if w:
        [
             alert_.append_msg(warning.message.args[0], type_="warning")
             for warning in w
         ]
```

To me there are multiple problems: 

1. the resulting messages are useless to debug what's happening as you don't have the full traceback as shown in this @BuddyVolly example:
 
![Bildschirmfoto 2021-10-07 um 13 26 09](https://user-images.githubusercontent.com/12596392/136389698-73c61c60-1a4f-4201-8926-e8d2831b19aa.png)

2. if you're not the author of the lib leading to the warning then there is nothing you can do
3. it provides a wrong idea to the end user; it feels like something went wrong when in fact everything has worked just fine

For me the `loading_button` decorator was mostly to avoid the crash of application (where you need to restart everything to get it running again) and provide some info in voila (where the console cannot be seen) to allows user to give us feedback on their problems. 

I think we've been one step too far as warning are for developers only and should only be displayed in the console when we run `no_ui.ipynb` notebooks.

What are your thoughts about this ? should we continue capturing warnings ?

**Comment by dfguerrerom** [comment]
Well, @12rambau, you're right!... when I envisioned this feature I was thinking more about how could we avoid creating validation messages in the `view` and instead of capturing them through the `model` without the need of sending there an Alert... but I didn't mean to display the third party package warnings, just ours!! What if we create our own `SepalWarning`? and we capture only this one?

**Comment by 12rambau** [comment]
I like this idea a lot !
