### ISSUE TITLE
in the `AssetSelect` object make the `get_items` an exposed function 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#323]
## Use case

I created a `ReclassifyView` and not only I want to have gee assets but more importantly I want to deal with images only. 

what I did is create a reclassify_view object and then changed the `type` member to `['IMAGE']`. Once done every press on reload will only retreive the images instead of IMAGES and TABLE. BUT the first display will retreive both. As a maintainer I know I can call `_get_items()` after init to update my modification but normal dev can't as the method is hidden in the documentation.

What do you think of making it a exposed method ?

**Comment by dfguerrerom** [comment]
We could make it a public method and would be ok, but what if we just convert the types arg into a trait and then we observe it by decorating the _get_items()?

**Comment by 12rambau** [comment]
>We could make it a public method and would be ok, but what if we just convert the types param into a trait and then we observe it by decorating the _get_items()?

way better

**Comment by dfguerrerom** [comment]
You can observe any `trait type`. `List` and `Dict`, however, are mutable objects, which means that the observe method won't trigger an event if you change its elements, i.e. (`List([1,2])[0] = 1`; `Dict({})["x"]=1`), but you can trigger an event by assigning again the `dict `or the `list` (i.e.` List([1,2]) = [0]`, `Dict({}) = {"x":1}`... and that's exactly what we do in the `_get_items()` method.

**Comment by 12rambau** [comment]
ahhhh that's extremly useful, so you can observe assignment but not mutation, ok then I know what to do !

**Comment by dfguerrerom** [comment]
exactly! you can observe assignments in mutable objects and changes in immutable.
