### ISSUE TITLE
should we override all ipyvuetify components ?

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#339]
I don't really like to use `su.hide_component(v.whatever)` all over the place when we have a nice `hide()`method built-in the normal widgets. 

What would you think if sw was including a overwritten version of all the widgets inheriting from the original `v.widgets` + `SepalWidget` ?

**Comment by dfguerrerom** [comment]
Yes, I agree with you, I would prefer to use our SepalWidget methods... didn't you make the PR in the ipyvuetify repository to have this natively there?

**Comment by 12rambau** [comment]
it's in ipyvue and I think it's unpublished yet. But for example if we set other things in SepalWidget: 

- https://github.com/12rambau/sepal_ui/issues/341
- https://github.com/12rambau/sepal_ui/issues/342

Then I would like to use it everywhere.

**Comment by 12rambau** [comment]
side note, the PR I made in ipyvue is a class_list object based on https://developer.mozilla.org/fr/docs/Web/API/Element/classList MDN classList object. meaning that the `hide` method that we have that we have (saving the old_class and only set "d-none" is more advanced than the pre-build one.
