### ISSUE TITLE
refactor members declaration in all classes

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#340]
I discovered recently (https://stackoverflow.com/questions/9305751/how-to-force-ensure-class-attributes-are-a-specific-type) that you can est up class members out of the __init__ functions and give them a specific docstring and type. 

I'm working to complete the new documentation of the API content and I'll see if I can safely refactor member declaration to make it compliant with the latest PEP.

I'll also try to investigate to pros and the cons of using traitlets systematically

**Comment by dfguerrerom** [comment]
What PEP are you referring to? Why we would want to force some specific types instead of doing the validation through traits?

**Comment by 12rambau** [comment]
PEP 242 If I trust the SO answers. But don't be fooled, there are no type enforcement here (as usual in Python), it's just to help linter and sphinx. ex: 

```python

class A()
   a: int
   b: str
```

**Comment by dfguerrerom** [comment]
Anyways, if we would want to use the typing in the methods, we could check https://docs.python.org/3.8/library/typing.html

**Comment by 12rambau** [comment]
I remember hitting into this typing lib some tile ago, in the end I realized it's again (and as usual in Python) just indications. 
You have no idea how disappointed I was ;-)
