### ISSUE TITLE
add a `add_tooltip` method

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#342]
I don't know where to start from, tooltip syntax is super tedious and I would like to find a way to make it easier. 

My first thought is: it's mainly useful for btn so I was thinking of adding a add_tooltip method to the btn object. that would return the tooltip (and not the btn) and that's where it can be tricky. 

Also it could be added to `SepalWidget` but I' would argue that nobody will add a tooltip to a `sw.Tile` object.

I'm open to discussion, this issue is just a reminder

**Comment by dfguerrerom** [comment]
Yes, as we have talked about before, that's one of the limitations of the ipyvuetify `Tooltip`'s... at the end you'll have to have two widgets, the tooltip to the frontend and the wrapped one... it would be nice if you can come up with a solution ;).
