### ISSUE TITLE
Local raster are not displayed in SEPAL dashboard apps

### ISSUE THREAD

**Issue by ingdanielguerrero** [12rambau/sepal_ui#35]
Local raster images are not being displayed in voilá dashboards nor Jupyter SEPAL dashboards, the problem comes up when the `xarray_leaflet` module is [stating](https://github.com/davidbrochart/xarray_leaflet/blob/700a91c9310fe4406ed322c7f9c25b90cddf46ab/xarray_leaflet/xarray_leaflet.py#L265) the `base_url`, using the 'notebooks' word.

The sepal module dashboards are being stored in /shared/notebooks/, so the condition is trying to find the last 'notebook' word, but as there are two occurrences in the URL, it will take the second, causing confusion and pointing to nowhere.

Three solutions come up to my mind:

- Post to `xarray-leaflet` and try to change the way to get the base URL (could be using the first occurrence instead of the last).
- Move the SEPAL dashboards to another folder
- Change the structure in the `xarray-leaflet` module by forking it.

**Comment by 12rambau** [comment]
fix in [PR#29](https://github.com/davidbrochart/xarray_leaflet/pull/29#issuecomment-721814998)
