### ISSUE TITLE
List of gdal command required in sepal_ui 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#4]
Add in the comment the `gdal` command that you would like to see in sepal_ui
Remember that a lot of them are already bind in `osgeo.gdal`

### Updated list of the oft functions in sepal_ui
- [x] gdal_merge.py
- [ ] gdal_calc.py

**Comment by ingdanielguerrero** [comment]
I'm not sure why we would like to add gdal methods to the sepal_ui, could this be outside from the module scope? If some new app needs that, I think the better solution could be including it but in its own library.

**Comment by 12rambau** [comment]
It was a requirement asked by Rémi. The advantage is that it's made to work with an Alert as an output

**Comment by 12rambau** [comment]
Useless now that I've started a lib dedicated to manipulation function
the rep is here https://github.com/12rambau/SGT
The gdal file will be removed once I'm 100% sure that no function is using it any more in modules that are already in prod
