### ISSUE TITLE
Interact with navigation drawers

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#415]
Sometimes is useful to pass some data from the module model to the app environment and so far we do not have this implementation.

We can add two simple methods to the drawers so they can update their state with icons, badges, and so.

**Comment by 12rambau** [comment]
thanks for the PR, I undestand better what you want to achieve. Could you describe 1 single use case to help me understand how I could use it as well ?

**Comment by dfguerrerom** [comment]
In almost every module, the processes are sequential and the steps are associated with the previous item, i.e., you select the area of interest in the first drawer, and in the second you calculate the zonal statistics... we can change the state of a given variable in the model and then the drawer will listen to it and will draw the user's attention by adding a "red circle", basically, will tell the users that they can now go to the next step.

**Comment by 12rambau** [comment]
Excellent I love the idea.
