### ISSUE TITLE
there's a dot in the bottomright corner of the map

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#456]
I don't know where it's comming from but there's a dot in the bottomright corner of the map. I t needs further investigatio and if we can get rid of it it would be great.
![Capture](https://user-images.githubusercontent.com/12596392/165972050-67eee7cb-7d28-4174-ad5d-14c836e187cc.PNG)

**Comment by dfguerrerom** [comment]
with the latest SepalMap refactoring, have you managed it? or does it remain there?

**Comment by 12rambau** [comment]
It's still there but as I go down the refactoring path, maybe I should take care of it in the PR as well

**Comment by 12rambau** [comment]
that was the empty output from the inspector. That will be corrected in the map refactor
