### ISSUE TITLE
Drawing controls are not displayed in Jupyterlab with ipyleaflet==0.16.0

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#509]
As described in the title, the drawing controls are not displayed when using `ipyleaflet==0.16.0`, however, they are in voilá and/or when using Jupyter notebooks.

![image](https://user-images.githubusercontent.com/12363250/174769616-f7d9961b-cd99-4ac8-99a2-9440983f8152.png)

**Comment by 12rambau** [comment]
That's also working in Jupyter Notebook so the problem is related to JupyterLab itself. Looking at the inspector, in Lab the drawing tag is empty all the time when it should be filled with widget. I opend an issue ion ipyleaflet for that: https://github.com/jupyter-widgets/ipyleaflet/issues/1014

**Comment by 12rambau** [comment]
that was an environment conflict between JupyterLab and Python
