### ISSUE TITLE
planet API is making the CI crash

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#519]
All the rececent CI based on master are crashing as new deprecation warning are raised during the Jupyter-sphinx execution: 

> WARNING: Cell printed to stderr:
[21](https://github.com/12rambau/sepal_ui/runs/7168163180?check_suite_focus=true#step:9:22)
/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/planet/api/__init__.py:38: ClientV1DeprecationWarning: The planet.api module is deprecated and will be removed in version 2.0.0. For more details please see the discussion at https://github.com/planetlabs/planet-client-python/discussions.

I think we need to have a look to see if we need to fix planet version

**Comment by 12rambau** [comment]
The solution might be here: https://github.com/jupyter/jupyter-sphinx/issues/178

**Comment by dfguerrerom** [comment]
Anyways I think we have to move to version 2. v1 is ugly.

**Comment by 12rambau** [comment]
I made sure sphinx stop throwing warning to our face, we'll move to v2 whenever we want
