### ISSUE TITLE
Change to free tagged icons v.5 on fontawesome?

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#576]
Our File Input menu now is not displaying most of the different icons. I think we have to decide if we are going to have a paid version (and wait) or keep using v.5 but with free tagged icons to avoid this issue. What do you think?

![image](https://user-images.githubusercontent.com/12363250/185958982-c26cffd1-64ca-48d1-9552-1c2dc8c8c0b2.png)

**Comment by 12rambau** [comment]
the V6 has been integrated the pydata-sphinx-theme I want to see how they port the old icons into the new interface (`fa-solid fa-...`). I think it will be seamless so we won't have to hard change everything in every application. 

The V6 is including lot's of new icons I think it will cover most of our needs
