### ISSUE TITLE
find layer by unequivocal key in a map

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#593]
**Is your feature request related to a problem? Please describe.**
I'm developing a module and using the translator to have a 100% translatable app, the thing is that even though I can use a translatable name as a name to a layer, this is prone to errors.

**Describe the solution you'd like**
I would like to be able to use both `name` and a display `label` in the `add_layer` method, so the name can be used unequivocally as a key to performing search operations and the label will be used only to visualization purposes.

what do you think? @12rambau ?

**Comment by 12rambau** [comment]
That's the main reason I overwrite `add_layer` and `remove_layer` in the first place, to search for names in the list whatever the translation. To be fair it works without issues in the alert application, do you have an exemple in mind where only relying on the translator key is not sufficient ?

**Comment by dfguerrerom** [comment]
Yes, I know it works and I don't have an example where that is not enough, it is just I was not feeling comfortable when removing a map with a translated key instead of doing it just by its `key`. Tbh I don't think there will be a problem, it was just more for consistency.

**Comment by 12rambau** [comment]
If you find a nice implementation without making `find_layer` too big I'm happy with it !

**Comment by 12rambau** [comment]
I was diving in the code source of ipyleaflet for the earthengine branch and i found this 
https://github.com/jupyter-widgets/ipyleaflet/blob/3b3636fb3bf14ce9d050ab947cb1dde1dfe4d530/ipyleaflet/leaflet.py#L1294

```python
 def add(self, layer):
        """Add a new layer to the group.
        Parameters
        ----------
        layer: layer instance
            The new layer to include in the group. This can also be an object
            with an ``as_leaflet_layer`` method which generates a compatible
            layer type.
        """

        if isinstance(layer, dict):
            layer = basemap_to_tiles(layer)
        if layer.model_id in self._layer_ids:
            raise LayerException('layer already in layergroup: %r' % layer)
        self.layers = tuple([layer for layer in self.layers] + [layer])
```

Looking at the definition of `add` it seems to me that layers already have an unequivocal key: `model_id`. If you want to experiment be my guest I' refactoring the tests and that's clearly eating all my time ;-)

**Comment by 12rambau** [comment]
I confirm that each added layer is embeding a model_id that is unique and unequivocal. 

```python
from sepal_ui import mapping as sm 
from sepal_ui.scripts import utils as su 
import ee

su.init_ee()

map_ = sm.SepalMap()
dataset = ee.Image("CSP/ERGo/1_0/Global/ALOS_mTPI")
map_.addLayer(dataset)

[l.model_id for l in map_.layers]
```

I think we can start from this. What would you think if find_layer was also looking for these `model_id` to identify layers ? 
As this is a hidden parameter we would need to tune the add_layer method to return the `model_id` as well

**Comment by dfguerrerom** [comment]
but I think that `model_id` is too unique to be used as key to remove... some times you just want to remove a layer multiple times, i.e.: you add an "aoi", then you restart that process and you search the "aoi" layer by the "aoi" name, and the name is fixed... if we use `model_id` we will have to find the specific id... to me that would be too complicated for something simple...

**Comment by 12rambau** [comment]
agreed, also worth mentioning that in SepalMap, all names are unique keys as we prevent addition of extra layers using the same name.
