### ISSUE TITLE
Resize event is not triggered

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#709]
I was working on some PySMM issues and I came across the resize trigger issue. The JavaScript snippet doesn't run. Could it be related to the fact that the template is not part of the instance?

https://github.com/12rambau/sepal_ui/blob/5727303e2a0e853236b6028c58067f5dd680ff38/sepal_ui/frontend/resize_trigger.py#L23

**Comment by 12rambau** [comment]
If it's not included I'm positive it won't work but why is it not imported in this instance?

**Comment by dfguerrerom** [comment]
you could use the "blame" button you showed me ?

**Comment by dfguerrerom** [comment]
ok, but `rt` is not imported already in app_bar?

**Comment by 12rambau** [comment]
it is but is it displayed in the html output ?  maybe that's just a matter of displaying things, could you test what happens if the display method is moved from the frontend file to the `app_bar` itself ?

**Comment by dfguerrerom** [comment]
actually the error is that we are not reading the `js` `Path` as text
