### ISSUE TITLE
no pymodule is installed when running -e installation

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#714]
I recently reinstalled all my environment and specifically the sepal_ui lib from my local clone: 

```
pip install -e sepal_ui/
```

It seems since we moved to .toml file we missed something as the module is not included in the .local folder anymore: 

```
.local
└── lib
    └── python3.8
        └── site-packages
            ├── __editable__.sepal_ui-2.14.2.pth
            └── sepal-ui-2.14.2.dist-info
                └── ...
```

**Comment by 12rambau** [comment]
I made some expriences with other libs and it seems unrelated. I'll close when the SO question will get an answer: 
https://stackoverflow.com/questions/75234789/pip-install-e-is-not-resolved-by-jupyterlab

**Comment by dfguerrerom** [comment]
I was trying to test the `layers` branch, but came across with this error, is it related?

```Python

ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.


```

**Comment by 12rambau** [comment]
No. yours is because the requirements have changed since the last time you installed it (I moved the databases from .csv to .parquet) so there are extra libs. You can simply install `pyarrow`.
