### ISSUE TITLE
make get_children recursively again

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#744]
previous implementation used recursion to find all children within the widget that matches with the query, now it returns only first level of matching children, could we make it reclusively again?

**Comment by 12rambau** [comment]
I did it on purpose to make it faster, it would be easy to reverse it but do you have a use case example where a search should return the parent and the children?

**Comment by dfguerrerom** [comment]
I don't meant to return the parent and the children. The purpose is to find children, grandchildren, great-grandchildren and so on... 
I started to use that in `sepal-mgci`: https://github.com/sepal-contrib/sepal_mgci/blob/9ce04f34831258317339e90bf4ac32c051f810aa/component/widget/calc_params.py#L76

I search elements which are within a ListItem>ListContent>....>Html... instead of assigning them to a class variable, I make them "anonymous" with an attribute id...
