### ISSUE TITLE
DatePicker renders duplicated when multiple created

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#746]
After `sepal_ui>=2.13.0` when we implemented `layout_kwargs` attribute, an strange behavior started to appear: when multiple `DatePicker` are created and displayed in the same component, in somehow they start sharing its attributes, weird.

Try the following:

```python
import sepal_ui.sepalwidgets as sw


class DateSelector(sw.Layout):
    
    def __init__(self, *args, **kwargs):
        
        super().__init__(*args, **kwargs)
        
        self.w_unique_date = sw.DatePicker(label="Date")
        self.w_ini_date = sw.DatePicker(label="Start date")

        self.children = [
            self.w_unique_date,
            self.w_ini_date
        ]

date_selector = DateSelector()
date_selector
```

If you click over one of the date pickers, the other will be displayed.

![image](https://user-images.githubusercontent.com/12363250/217365578-692a8c45-18e1-47c3-9c4e-2bcf5243d2e1.png)

After a lot of tests, I isolated the problem, but I cannot explain the reason of this... the problem can be solved in several ways:

- remove `layout_kwargs` from the `__init__` method.
- reassign `layout_kwargs={]` within the __init__ method.
- create a DatePicker as: DatePicker(layout_kwargs={})

Method 1 and 2 would drop the `layout_kwargs` purpose: customize the layout from the initialization of the instance.
Method 2 is horrible, I won't opt for this.

First thing, I would like to have an explanation for this, perhaps if we nail the problem we could solve it and keep layout customization support, otherwise, I would drop it.

What do you think @12rambau, do you want to give a try and confirm you have the same issue? and if you can try to give an explanation?

**Comment by 12rambau** [comment]
I was starting to experience the same but I didn't find the time to do the investifation you produced, thanks! 
Looking at your example it seems the problem is rooted more deeply as the 2nd label is ignored: both are using "date".

**Comment by 12rambau** [comment]
I think that was a mutable object issue. I found a trick and updated my datepicker branch accordingly
