### ISSUE TITLE
custom frontend?

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#777]
I would say that all the modules from `sepal-contrib` are using the same frontend design specified in `sepal-ui`, however, I have  found some specific cases in which I would like to change something specific on an app that I don't want to be changed in others, and something that I can only perform with `js` or `css` tricks...

What do you think if we incorporate a `CustomCSS` class that receives a `.css` file and then incorporates it in the UI?, it will be used for specific case of uses where the developer wants to implement a custom style.

My concern is that perhaps by doing this, some apps could be too different? should we restrict? do you see a problem with this?... and furthermore, if someone find a bug in the styles, the error could be fixed on the specific app but not shared among the whole framework... thoughts?

**Comment by 12rambau** [comment]
Do you consider my last message as a decent workaround or do you still want to add a `CustomCss` and `CustomJs` ? 

This can also be documented somwhere so that people know it's possible
