### ISSUE TITLE
add timestamp in output messages

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#8]
In the Alert class, we are adding a message to che object children.

For output that always display the same message (gee interactions for example) I think we could add the timestamp to show the end user that the process is still running :

here is a proposal solution : 
```
def add_msg(self, msg, type_='info'):
        self.show()
        self.type = type_ if (type_ in self.TYPES) else self.TYPES[0]
        self.children = [msg]

def add_output(self, msg, type_'info'):
    current_time = datetime.now().strftime("%Y/%m/%d, %H:%M:%S")

    self.show()
    self.type = type_ if (type_ in self.TYPES) else self.TYPES[0]
    self.children = [
        v.Html(tag='p', children=['[{}]'.format(current_time)]),
        v.Html(tag='p', children=[msg])
   ]

**Comment by ingdanielguerrero** [comment]
Yes, I agree with you in this new method... however I think its name it's a little confusing... what do you think about `add_live_msg()`, or something more indicative?
