### ISSUE TITLE
Locale spanish missing type

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#823]
As it was reported here: https://collaborative-learning.fao.org/mod/forum/discuss.php?d=10759#p37702, there's an error when users change the language of the modules to Spanish, 

`ms.widgets.asset_select.types` will return `('Tabla/Vector', 'Algoritmo', 'Directorio')` with ES, while it has to return 
`('Raster', 'Tabla/Vector', 'Image collection', 'Algoritmo', 'Directorio')`

**Comment by 12rambau** [comment]
they are stored here: https://crowdin.com/translate/sepal-ui/44/en-es?filter=basic&value=0
