### ISSUE TITLE
Consider drop jslink usage in favor of native traitlets links

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#828]
as reported in https://github.com/sepal-contrib/alert_module/issues/105 and due to an incompatibility between some versions of `ipywidgets` and `voila`, all the events/widgets that are imported from `ipywidgets` doesn't work on `voila`, we could consider dropping `jslink` usage in favor of `link` from `traitlets`. 
Currently there's two objects that are being affected by this issue https://github.com/12rambau/sepal_ui/blob/4fc5ac1e2473fddf736a5fac3f5c2eddc07b453a/sepal_ui/sepalwidgets/alert.py#L285 and https://github.com/12rambau/sepal_ui/blob/4fc5ac1e2473fddf736a5fac3f5c2eddc07b453a/sepal_ui/sepalwidgets/inputs.py#L554

some refs: 

- https://github.com/openforis/sepal/pull/244
- https://github.com/voila-dashboards/voila/issues/1202#issuecomment-1255040572

**Comment by 12rambau** [comment]
I don't see any reason to coninue to rely the js binding if the traitlets is more robust. happy to review a PR
