### ISSUE TITLE
is precommit working?

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#836]
I noticed it after committing on `localtileserver` branch, pre-commit hooks did not run, that's not normal, right? I did a random change on a test_commit branch and it passed (https://github.com/12rambau/sepal_ui/commit/96b6fb425558103b153cf3b3b26961b0194474b8).

**Comment by 12rambau** [comment]
pre-commit are run in local only if they are installed and they are run as part of the unit.yml test only when PR to main. 

so if the question is about local env maybe run: 
```
pre-commit install
```

and if it's about the CD/CI, you need to make PR to check if it runs.

**Comment by dfguerrerom** [comment]
yes, I hadn't installed it on my side. I thought and error came up when you push something without rules in the repo.

**Comment by dfguerrerom** [comment]
something changed... before you wouldn't have been able to push if you hadn't run the `pre-commit` hooks... in my last PR I was able to push without having `prettier` installed and so that hook didn't work...

**Comment by 12rambau** [comment]
where are you pushing from ?

**Comment by 12rambau** [comment]
any update on this one ?

**Comment by dfguerrerom** [comment]
I believe it was failing because I didn't have install `pre-commit` on my local branch, and test didn't run on github because of something, but now it seems to be okay.
