### ISSUE TITLE
make Alert.clear only clear

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#9]
For sementic reason I disagree with the way Alert.clear is designed : 
```
def clear(self):
        self.hide()
        self.children = ['']
```

here the method hide AND clear. I think we must keep these methods separated and for clarity in codes do them manually

**Comment by 12rambau** [comment]
I'm actually using it and I think I understand what you meant by 'clear'. It's more a reset. 
And the behavior you're looking for is "if there is nothing to display then hide it"

I'll change the name to reset to avoid confusion and implement your behavior

**Comment by ingdanielguerrero** [comment]
Agreed!
