### ISSUE TITLE
Ipyleaflet not compatible with jupyterlab 4

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#901]
As I commented on https://github.com/openforis/sepal/issues/304, `ipyleaflet` events don't work with `Jupyterlab 4`. The problem was related to incompatibility of `js` libraries on the build, it was solved on https://github.com/cdanielw/ipyleaflet.
To speed up the implementation process I suggest to use that fork in this project.

**Comment by 12rambau** [comment]
solved by https://github.com/jupyter-widgets/ipyleaflet/issues/1125
