### ISSUE TITLE
don't retrieve the geometries

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#919]
Is there a need to "download" the AOI if the `AoiModel` is instantiated with the  `gee` parameter? 
If I create a GEE app, there are only few and specific cases (or is there even any?)  where I want to retrieve the features from GEE and then store them as `GeoDataFrame` in the object,
I think we should not make this expensive process as the default  behavior every time an AOI is created, this is not useful, and it is even worst if a vector file is selected from the client side: it uploads it and then it downlaods it.

**Comment by 12rambau** [comment]
my inistial though was consistency. 
Whatever we do we always have the same thing: a GEE asset and a geodataframe available.
What could be done is to create them as properties and only compute it upon request.

**Comment by dfguerrerom** [comment]
Actually, that's not always the case:
- `from_asset` (gee) method doesn't create a `gdf` (and it shouldn't).
- `from_points`,  `from_vector` and `from_geo_json` only create the `feature_collection` if it is requested.
- `from_admin` is the only `gee` method which also creates a `gdf`, and I think we do that because we need to set a name for the feature?
